### ISSUE TITLE
Add an option to damage rolls to freely customise graze damage

### ISSUE THREAD

**Issue by stanavdb** [stanavdb/cosmere-rpg#102]
**Is your feature request related to a problem? Please describe.**  
Currently all damage rolls (as part of an attack) must use skill/attributes mod for graze. This works fine for character but adversaries are often non-standard and don't fit into this paradigm.

**Describe the solution you'd like**  
Add some options to use custom graze damage in the form of a formula, instead of the default calculated. 

**Describe alternatives you've considered**  
-

**Version**  
0.1.1

**Additional context**  
Reported by `@doc_sun` on Discord.

**Checklist:**
- [x] I have searched the existing issues to ensure this feature has not already been requested.

**Comment by zithith** [comment]
commenting for assignment
