### ISSUE TITLE
Contextmenu error in console

### ISSUE THREAD

**Issue by stanavdb** [stanavdb/cosmere-rpg#104]
**Describe the bug**  
When opening certain Application (character/adversary sheet for example) an error appears in the console. This does not seem to cause any actual problems, though we might simply be overlooking them.

**To Reproduce**  
1. Load up a world
2. Open a character sheet
3. Close the character sheet
4. Open up the character sheet again
5. Check the console for the error

**Expected behavior**  
No error should be thrown.

**Screenshots**  
![image](https://github.com/user-attachments/assets/1462b9f3-7749-4e21-93e6-0039bda475ad)

**Foundry VTT Version**  
12.331

**Cosmere RPG System Version**  
0.1.1

**Checklist:**
- [x] I have searched the existing issues to ensure this bug has not already been reported

**Comment by tbytnar** [comment]
Fixed by PR #142
