### ISSUE TITLE
Overflow of text in Goal Section

### ISSUE THREAD

**Issue by Doc-Sun** [stanavdb/cosmere-rpg#112]
**Describe the bug**  
The Goal Section does not expand to accommodate large goal descriptions

**To Reproduce**  
_Steps to reproduce the behavior:_
1. _Go to the goal section and create a new goal_
2. Type a long sentence and then hit enter

**Expected behavior**  
The field area should expand to accommodate text.

**Screenshots**  
![image](https://github.com/user-attachments/assets/f0a76721-8d43-49b2-81b6-15855f21be12)

**Foundry VTT Version**  
Foundry VTT 12 Build 331

**Cosmere RPG System Version**  
0.1.1

**Browser**  
Firefox

**Checklist:**
- [ .] I have searched the existing issues to ensure this bug has not already been reported

**Comment by tbytnar** [comment]
Adjusting the CSS for the goals and connections list got me here:
![image](https://github.com/user-attachments/assets/b09a536b-c925-46a7-9609-44fa4d625341)

@Doc-Sun does this look how you'd imagined?

**Comment by Doc-Sun** [comment]
The Latin frightens me lol. Nah looks like I expected it to work. Though it still is quite tight on the edges. Maybe a little padding on the top and bottom of each goal.

**Comment by RostCS** [comment]
Issue resolved in [this PR](https://github.com/stanavdb/cosmere-rpg/pull/140)
