### ISSUE TITLE
Make Rolling Without a Dialog the Default

### ISSUE THREAD

**Issue by MangoFVTT** [stanavdb/cosmere-rpg#114]
**Is your feature request related to a problem? Please describe.**  
One of the major points of annoyance in the dnd5e system on Foundry is the amount of clicks one needs to go through in order to get to a chat message, particularly for DMs that are rolling a lot of characters all at once. This problem is way less for this system, but every roll having a dialog popup to raise stakes and all that will still, in the long run, be a LOT of extra clicks. The majority of times, the roll that people want will be the default configuration of the dialog, so needing to accept that dialog is a redundant extra click.

**Describe the solution you'd like**  
I would like to propose the following workflow for a regular roll:
-  If the user simply clicks on a skill or action, immediately roll with the default roll configuration. No raised stakes, no advantage/disadvantage, just a simple basic roll (we can make this behaviour swappable with the "show dialog" behaviour via a setting if desired)
- If the user Shift-clicks (we can and should set this up so the key modifiers are all customisable) a skill or action that has a roll, set the d20 to Advantage and otherwise keep the default configuration of everything. There's always a d20 in a test, so it is by definition the most common target for advantage. Shift-clicking something that has no roll simply doesn't do anything different than a normal click.
- If the user Ctrl-clicks a skill or action, same as above, but disadvantage.
- If the user R-clicks (or some other key, doesn't matter) a skill or action, raise the stakes on the roll and otherwise keep the default configuration of everything
- If the user Alt-clicks a skill or action, show the full roll dialog and allow 100% customisation of the roll as it is now (or vice versa if the setting proposed above is a thing we want)

In this way, we cover the bases for all the most common types of roll, while only requiring a single click for the user to get what they want. The dialog remains an option for comprehensive customisation of the roll.

The simple way to do this would be to pass advantage/disadvantage/raise stakes as config options from a preliminary function that detects if key modifiers are pressed when the click is made.  The config should also have a fastForward value that is set to true by default and false if the relevant modifier is clicked. This also opens up these options for macros in future, so a user can simply call with the relevant config options to get what they want without even click modifier keys.

**Additional context**  
I have some history with this from the dnd5e side, as developer for [Ready Set Roll](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e), which a lot of people consider a must have to skip the billion dialogs that dnd5e forces on you. What I'm proposing is in-line with the behaviour that module creates for rolling workflow, so it is a very tried and tested method.

**Comment by MangoFVTT** [comment]
Just a note that, having some experience with this particular aspect of a system already, I wouldn't mind doing it myself (time allowing), but I would like to put the point forward for discussion first

**Comment by Rymliez** [comment]
Hello, I am a person without any experience in the art of programming, but I would like to give my opinion about it. I like the idea that is proposed but perhaps it could be the opportunity to solve the biggest weakness of foundry with respect to the players to make rolls using your phone, as you see this will be a problem with the proposed method, could be that instead of requiring keys would be a small menu that arises by holding down the mouse button (advantage and disadvantage), this would solve the problem of both parties and would also be much faster to learn for beginners.

**Comment by zithith** [comment]
For the sake of record:
There has been a fair amount of discussion on this on the discord, but the general feeling seemed to be that [for now] we think having the modifier keybinds is helpful and even a setting to let users skip the dialog is great, the default should be to show the dialog, especially as in this system 'vantage isn't necessarily always placed on the d20.

Judging by the #117 changelist this is what Mango has worked towards.

**Comment by MangoFVTT** [comment]
Correct, though a slight addendum that we don't want to have modifiers for all kinds of advantage, just the d20. If advantage on others are desired then the config can always be used, or in the future retroactive roll editing
