### ISSUE TITLE
Incorrect font in "purpose and obstacle" field

### ISSUE THREAD

**Issue by LLilliputian** [stanavdb/cosmere-rpg#127]
**Describe the bug**  
Currently the "purpose and obstacle" field is using Calibri font.
Reported by @theflyingp1g on 21/10/2024

**To Reproduce**  
1. Open character sheet
2. Navigate to "purpose and obstacle" field
3. Enter text in field
4. Text will be in Calibri font

**Expected behavior**  
Text in field should be the same as other body font

**Checklist:**
- [x] I have searched the existing issues to ensure this bug has not already been reported

**Comment by RostCS** [comment]
Resolved in #129
