### ISSUE TITLE
Expand character data model

### ISSUE THREAD

**Issue by stanavdb** [stanavdb/cosmere-rpg#5]
The character data model needs be expanded with several additional fields to hold the following:
- Spheres / currency
- Injuries
- Purpose, obstacle & goals
- Connections
- Bio, appearance & notes

We'll need to think about we model these field

blocks #4

**Comment by jsc17** [comment]
For spheres, the beta rules clearly state the game will only track diamond marks, assuming that your actual wealth is an equally valuable assortment of spheres. Is there any reason to track anything more specific than that for the systems purposes?

**Comment by stanavdb** [comment]
> For spheres, the beta rules clearly state the game will only track diamond marks, assuming that your actual wealth is an equally valuable assortment of spheres. Is there any reason to track anything more specific than that for the systems purposes?

I think we should set it up as generic as possible so that can track various different currencies, all at once if needed. That way we can deal with the various currencies throughout the Cosmere and we're not having to deal with data model migrations later.

Maybe something along the lines of an array field holding the following schema?:
```js
{
    "type": "CURRENCY_TYPE", // The type of currency e.g. Spheres
    "denominations": [
        {
            "id": "DENOMINATION_ID", // The denomination e.g. Marks
            "amount": 100 // The actual amount the character has
        }
    ]
}
```

**Comment by jsc17** [comment]
Yeah, I was overthinking it. I knew it would be simple, but I was wondering if we should include chips, marks, and broams for some reason. The game seems to be fine abstracting it away to just marks, so we should as well. 

The schema looks good unless there ends up being something more nuanced we need to track, but I can't think of anything at the moment.

**Comment by NoahJGersh** [comment]
Injuries are very nebulously defined, which is nice for narrative freedom but tricky for implementation.

Do we just want to track the number of current injuries a character has, in the character schema? We'll probably also want an Injury item type so users can store the duration, location, effect, etc.

**Comment by NoahJGersh** [comment]
Working on some implementation of the currencies specifically, and I'm thinking we might want to shift to a map. It's going to be much easier to establish the data model if we store it as a `SchemaField` rather than an `ArrayField`.

E.g.
```
{
    "spheres": {
        "denominations": [
            {
                "id": "chips",
                "amount": 100
            }
        ]
    },
    "imperials": {
        "denominations": [
            {
                "id": "boxings",
                "amount": 10
            }
        ]
    }
}
```

At that point we could also reassess how we organize the denominations, but this gives us space to derive a `total` for each currency that's computed from the denominations, if we wanted.

The question is, is that too unwieldy, especially as more currencies get added? Is there some simple way to define all of the current ArrayField options using the config that I'm just not seeing? Or we could just not constrain the actual currency types/denominations to what's in the config, but then you have people breaking up their spheres into boxings and broams.

Just some food for thought; I'm going to stop working for the night anyways!

**Comment by stanavdb** [comment]
For the currencies; I think `SchemaField` is absolutely the way to go. Perhaps we should specify the conversions and base denomination in the global config for each currency? That way we can add a derived field to each currency for the total (and allow for easy conversion to any other denomination of that currency). Though maybe this is overkill for our needs.

Something along the lines of:
```js
// Global config
{
    ....
   
    currencies: {
        spheres: {
            denominations: [
                {
                    id: 'chips',
                    label: '<LABEL>',
                },
                {
                    id: 'marks',
                    label: '<LABEL>',
                    base: true,
                    conversionRate: 5 // The amount to DIVIDE the previous denomination by to convert it to this. E.g. there's 5 chips to 1 mark
                },
                {
                    id: 'broam',
                    label: '<LABEL>',
                    conversionRate: 4
                }
            ]
        }
    }
}

// Schema
{
    "spheres": {
        "denominations": [
            {
                "id": "chips",
                "amount": 100
            },
            {
                "id": "marks",
                "amount": 5
            },
            {
                "id": "broam",
                "amount": 1
            }
        ],
        "total": 29 // Derived value, in marks
    }
}
```

Another interesting point is that for spheres specifically we also need to be able to track if they are dun or not. Maybe we set those up as additional denominations? I'm unsure on this point still.

**Comment by NoahJGersh** [comment]
Trying to look for some low hanging fruit to add to the model.

Biography and notes should absolutely just be `HTMLField`s... but what about appearance? Do we just want to give players another `HTMLField` to describe the look of their character?

**Comment by stanavdb** [comment]
Closing this issue as the data model necessary for release 0.1.0 is complete. See #41 for remaining data model.
