### ISSUE TITLE
Add theme support

### ISSUE THREAD

**Issue by stanavdb** [stanavdb/cosmere-rpg#71]
**Is your feature request related to a problem? Please describe.**  
We want to support a different themes for sheets (Actor/Item, possibly other UI elements as well) for all the various Cosmere worlds that will be released. These themes will be provided through their respective world modules. 

**Describe the solution you'd like**  
A robust theme system that allows us to provide themes in a standardised way through world modules. Users will need to be able to select their preferred themes, likely with some defaulting if only a single world module is used. 

**Checklist:**
- [x] I have searched the existing issues to ensure this feature has not already been requested.

**Comment by stanavdb** [comment]
We may be able to hook in to the already existing color scheme (light/dark) support present in ApplicationV2. Something we should look in to.

**Comment by stanavdb** [comment]
Relevant bug #80.

**Comment by MangoFVTT** [comment]
Started work on this, commenting here so you can assign me @stanavdb
