### ISSUE TITLE
Make injury roll visible 

### ISSUE THREAD

**Issue by stanavdb** [stanavdb/cosmere-rpg#86]
**Is your feature request related to a problem? Please describe.**  
When making an injury roll from the character sheet, it display the result in the chat, but does not show the roll (with modifiers etc.)

**Describe the solution you'd like**  
Make the roll + result visible in the chat message, and make it work with dice so nice.

**Describe alternatives you've considered**  
—

**Version**  
0.1.0

**Additional context**  
Reported by `@doc_sun` on Discord

**Checklist:**
- [x] I have searched the existing issues to ensure this feature has not already been requested.

**Comment by MangoFVTT** [comment]
Rolling this into #138 as per discord discussion
