### ISSUE TITLE
Item weights should default to lb unit

### ISSUE THREAD

**Issue by stanavdb** [stanavdb/cosmere-rpg#90]
**Is your feature request related to a problem? Please describe.**  
Item weights can be set and supports multiple units (though only 1 is configured right now, lb). However when creating a new item, the weight unit defaults to unset. 

**Describe the solution you'd like**  
Weight unit should default to lb.

**Describe alternatives you've considered**  
—

**Version**  
0.1.0

**Additional context**  
Reported by `@deathpote_` on Discord.

**Checklist:**
- [x] I have searched the existing issues to ensure this feature has not already been requested.

**Comment by NeilSorensen** [comment]
When testing on main with Foundry version 12 (build 331), weights are defaulting to lb correctly.

**Comment by stanavdb** [comment]
Thanks for verifying, closing this.
